name: gost
type: app
version: '2.11.1'
title: GO Simple Tunnel
summary: A simple security tunnel written in golang
description: |
  https://github.com/ginuerzh/gost
confinement: strict
grade: stable
base: core18
license: MIT
parts:
  gost:
    plugin: nil
    build-snaps: [go/1.13/stable]
    source: https://github.com/ginuerzh/gost.git
    source-subdir: cmd/gost
    source-type: git
    source-branch: '2'
    build-packages:
      - build-essential
    override-build: |
      set -ex

      echo "Starting override-build:"
      pwd
      cd $SNAPCRAFT_PART_BUILD
      GO111MODULE=on CGO_ENABLED=0 go build --ldflags="-s -w"
      ./gost -V

      echo "Installing to ${SNAPCRAFT_PART_INSTALL}..."
      install -d $SNAPCRAFT_PART_INSTALL/bin
      cp -v gost $SNAPCRAFT_PART_INSTALL/bin/

      echo "Override-build done!"
apps:
  gost:
    command: bin/gost
    plugs: 
    - home
    - network
    - network-bind

